// Generated by CoffeeScript 1.6.3
(function() {
  var cube, square;

  square = function(x) {
    return x * x;
  };

  cube = function(x) {
    return square(x) * x;
  };

  console.log(cube(5));

}).call(this);
